### ISSUE TITLE
ProxyChecker

### ISSUE THREAD

**Issue by rafedup27** [DefianceCoding/Anti-Proxy#1]
Tip, use string builders. Without them, yu always create a new string as strings are static! With string builder, you just overwrite the last string with a new one without actually creating new strings. This will be a huge performance impact. You can take a peek at my class from my plugin

**Comment by DefianceCoding** [comment]
Havent actually used this source in a while... it was something i lazily threw together for some players on spigot / server owners to mess around with and edit, not something in use today, but as of now everything comes from a JSON StringBuilder
